<?php


return [
    /*'DEFAULT_CONTACT_TELEPHONE'=>[
        'label'=>'网站固话',
        'permission'=>null,
        'type'=>'text',
        'default'=>'020-85581990',
    ],
    'DEFAULT_CONTACT_MOBILE'=>[
        'label'=>'网站手机',
        'permission'=>null,
        'type'=>'text',
        'default'=>'18826489686',
    ],
    'DEFAULT_CONTACT_USERNAME'=>[
        'label'=>'联系人',
        'permission'=>null,
        'type'=>'text',
        'default'=>'吕先生',
    ],
    'ONLINE_CHAT_SWITCH'=>[
        'label'=>'在线客服',
        'permission'=>null,
        'type'=>'checkbox',
        'options'=>[
            1=>'开启',
        ],
        'default'=>[
            1,
        ],
    ],
    'WEEKDAY'=>[
        'label'=>'工作日',
        'permission'=>null,
        'type'=>'checkbox',
        'options'=>[
            1=>'周一',
            2=>'周二',
            3=>'周三',
            4=>'周四',
            5=>'周五',
            6=>'周六',
            7=>'周日',
        ],
        'default'=>[
            1,2,3,4,5,
        ],
    ],
    'LEARNER_EXAM_DAYS_DELETED'=>[
        'label'=>'学员考试记录可删最近天数',
        'permission'=>'alllearner.process',
        'type'=>'text',
        'default'=>10,
    ],
    'GRADUATED_LEARNER'=>[
        'label'=>'已毕业学员数',
        'permission'=>null,
        'type'=>'text',
        'default'=>0,
    ],
    'RADIO'=>[
        'label'=>'Radio示例',
        'permission'=>null,
        'type'=>'radio',
        'options'=>[
            1=>'选项一',
            2=>'选项二',
            3=>'选项三',
            4=>'选项四',
        ],
        'default'=>3,
    ],
    'TEXTAREA'=>[
        'label'=>'Textarea示例',
        'permission'=>null,
        'type'=>'textarea',
        'default'=>"示例内容",
    ],*/
];
